### ISSUE TITLE
ModuleNotFoundError: No module named 'idr' : termseq-peaks

### ISSUE THREAD

**Issue by ramnageena11** [felixgrunberger/microbepore#4]
Hi Felix,
Got an error while ran the script for calling the peaks.

$ termseq_peaks /media/majorram/Analysis_Data/singhrn/transcriptome_atlas/tss/trimmed/output/barcode07.plus.bedgraph /media/majorram/Analysis_Data/singhrn/transcriptome_atlas/tss/trimmed/output/barcode08.plus.bedgraph /media/majorram/Analysis_Data/singhrn/transcriptome_atlas/tss/trimmed/output/barcode09.plus.bedgraph --peaks /media/majorram/Analysis_Data/singhrn/transcriptome_atlas/tss/trimmed/output/barcode789.plus.peaks --strand +
Traceback (most recent call last):
File "/home/majorram/anaconda3/bin/termseq_peaks", line 11, in
from peaklib.peaklib import idr_peak_calls
File "/home/majorram/anaconda3/lib/python3.9/site-packages/peaklib/peaklib.py", line 6, in
from idr import idr
ModuleNotFoundError: No module named 'idr'

**Comment by felixgrunberger** [comment]
I recommend looking into the documentation of the tmerseq_peaks package (https://github.com/NICHD-BSPC/termseq-peaks). Maybe installing the python module by `pip install idr` helps (if you installed termseq_peaks via pip).

**Comment by ramnageena11** [comment]
Hi Felix,
I tried as you suggested.
It says idr is already there.

$ pip install idr
Requirement already satisfied: idr in ./anaconda3/lib/python3.9/site-packages (0.0.1)

**Comment by ianzhao2022** [comment]
Please install the idr with conda, with pip install you might install a different version of idr. `conda install idr`
